### ISSUE TITLE
Move the `Resources` and `Bookmarks` components into the pages folder

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#108]
Tasks:
- create a `pages` folder in the `./src` folder
- move the `Resources` and `Bookmarks` components into the pages folder, making sure that everything is still working

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by Ngoakor12** [comment]
@Vinitvh Yes, yes you can
