### ISSUE TITLE
Make the search bar always visible and stick to the top like the nav bar

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#109]
The current current nav bar behavior is exactly what must be emulated/copied.It utilizes the css `sticky` position property. So what must happen is that we should be able to scroll until the search bar reaches the top from which it must then stick there like the nav bar.

**Comment by saifurrahmantanvir** [comment]
Hello,

I would love to fix this issue and contribute to this project.

**Comment by Ngoakor12** [comment]
No problem, knock yourself out. Let me know if you need clarity on anything

**Comment by saifurrahmantanvir** [comment]
![code-resource-tab](https://user-images.githubusercontent.com/77789469/192154545-539213e6-caaf-45aa-b269-fa6c7170dd68.png)
![code-resource-desktop](https://user-images.githubusercontent.com/77789469/192154548-034d49d5-259a-4b6c-9dba-99d6ee2f56ec.png)

I made the search bar sticky and moved it to the top on mobile and tablets. I think it looks better this way(personal preference). again if your want to move it back to the bottom, go to the CSS file and remove those styles where I added a comment like this "SEARCH_BOTTOM".

**Comment by Ngoakor12** [comment]
> ![code-resource-tab](https://user-images.githubusercontent.com/77789469/192154545-539213e6-caaf-45aa-b269-fa6c7170dd68.png) ![code-resource-desktop](https://user-images.githubusercontent.com/77789469/192154548-034d49d5-259a-4b6c-9dba-99d6ee2f56ec.png)
> 
> I made the search bar sticky and moved it to the top on mobile and tablets. I think it looks better this way(personal preference). again if your want to move it back to the bottom, go to the CSS file and remove those styles where I added a comment like this "SEARCH_BOTTOM".

The positioning of the search bar is fine, I've been meaning to change it anyway, you're good.

Can you fix the undefined bug with the resource count aswell? It should be `Resources (0)` when there are no resources
