### ISSUE TITLE
Add a "go to top" icon/button for scrolling to the top of the page 

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#114]
The issue is mostly self explanatory.

- Use this [icon/svg](https://api.iconify.design/ic:round-arrow-upward.svg) (green icon) from [this site](https://icones.js.org/collection/ic?s=up).
![image](https://user-images.githubusercontent.com/54069197/193407506-f967ee9d-e335-4345-958c-0459af0c48d3.png)

- Follow the current procedure of dealing with svgs's by adding them ti the `svgs.js` file and import it to wherever you want to use it from that file.
- Mockup design:
![image](https://user-images.githubusercontent.com/54069197/193411535-cb222c33-2dcb-495c-8b8c-deffe892f43e.png)
Note the drop shadow, go to [the figma file](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=0%3A1) for colour and dimension accuracy

**Comment by Reddomi** [comment]
Can I be assigned to this?

**Comment by Ngoakor12** [comment]
>Can I be assigned to this?

Yesss, give me a minute to mock out a design to make your life easier

**Comment by Ngoakor12** [comment]
There you go @Reddomi , updated instructions on the first comment. Let me know if you have any questions

**Comment by Reddomi** [comment]
Attempted to make a pull request - hopefully I did it right haha.

**Comment by Ngoakor12** [comment]
> Attempted to make a pull request - hopefully I did it right haha.

I'm sure you did fine, I'll have a look shortly
