### ISSUE TITLE
Add up to date screenshots of the desktop/larger site

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#116]
**Tasks:**
- [x] add some replacements to the pictures on `readme.md`
- [x] add as many screenshots as you can in `./docs/screenshots.md`

**Comment by Shivashish-rwt** [comment]
I can do that. Plz assign this task to me.

**Comment by Shivashish-rwt** [comment]
@Ngoakor12 
I wanna clear one thing. Do i have to add the screenshots in `./docs/screenshots.md`.

**Comment by Ngoakor12** [comment]
> @Ngoakor12 I wanna clear one thing. Do i have to add the screenshots in `./docs/screenshots.md`.

You have to add screenshots in two places:
- replace the current ones in `./readme.md`. 
- add as many as you can in `./docs/screenshots.md`

**Comment by Shivashish-rwt** [comment]
@Ngoakor12 
I can't locate to `./docs/screenshots.md`. Can u provide me with the full path please?

**Comment by Ngoakor12** [comment]
> @Ngoakor12 I can't locate to `./docs/screenshots.md`. Can u provide me with the full path please?

It's not there yet, so you have to create it
