### ISSUE TITLE
Style the scrollbar according to the theme of the site

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#117]
The white/grey-ish scrollbar looks really out of place currently, make it fit in.

**Comment by akssshh** [comment]
hey, @Ngoakor12 can you assign this to me?

**Comment by Ngoakor12** [comment]
@gogoiakash2311 there you go, let me know if you need me to clarify anything

**Comment by akssshh** [comment]
Ok, thanks for assigning me to this issue.

**Comment by pranavgoel29** [comment]
Oops, I forgot to ask for an assignment for this issue, I already did a PR solving this. @Ngoakor12

**Comment by akssshh** [comment]
No worries @Ngoakor12. Let @pranavgoel29 PR get merged.  I am unassigning myself from this issue.

**Comment by pranavgoel29** [comment]
> No worries @Ngoakor12. Let @pranavgoel29 PR get merged. I am unassigning myself from this issue.

Thank you, and once again sorry.

**Comment by pranavgoel29** [comment]
@Ngoakor12
I have made a PR please check #124

**Comment by akssshh** [comment]
It's okay @pranavgoel29
