### ISSUE TITLE
There are undesired server requests to /all route

### ISSUE THREAD

**Issue by timagixe** [Ngoakor12/coding-resource-finder#12]
Hi @Ngoakor12 !

STR:
1. open root page
2. open dev tools
3. go to network tab
4. observe extra requests to /all route

<img width="580" alt="Screen Shot 2022-04-05 at 10 06 08 PM" src="https://user-images.githubusercontent.com/60817786/161831414-12332bfb-6d24-4d3b-bd9c-4dba099f18a1.png">

**Comment by Ngoakor12** [comment]
Hey, thanks for finding this and letting me know. I wasn't aware and I don't think I would have found it. I'll definitely investigate further. Feel free to open a PR if you can.
