### ISSUE TITLE
Docs: Update `contributing.md` to add a section on the process to follow when you want to open PRs/Issues

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#120]
Currently the file only contains info on how to run the project locally. Some ideas on sections to include and what info I think should be mentioned:
- **Running the project locally**
  - Cloning the repo
  - Running the backend
  - Running the frontend
- **Opening an issue**
  - Search through the open issues and add one if you don't find it anything related.
  - Search through the closed/merged issues and if an issue you want to open has a merged PR, then reopen that issue with details on why you think the issue was not addressed.
  - Add labels related to your issue
- **Opening a PR**
  - Ask to work on an issue if you want to open a PR related to an issue, that way you can be assigned and others know you're working on it
  - Avoid opening a PR without an accompanying issue, so maybe open an issue to discuss if what you want to add to the project will be welcomed before you write complex features that may or may not be merged
  - Link issues related to your PR via the PR template or the development section on the right sidebar

**Comment by satyamgupta1495** [comment]
Heyy Ngoakor12, Do you want me to add all the points to contributing.md file? I can do that if you assign this to me.

**Comment by mohith2883** [comment]
Hey, I would like to work on this can you assign me . Thanks! @Ngoakor12

**Comment by mohith2883** [comment]
@Ngoakor12

**Comment by Ngoakor12** [comment]
@satyamgupta1495 you can work on it. @mohith2883 hardluck but someone already beat you to it

**Comment by mohith2883** [comment]
> @satyamgupta1495 you can work on it. @mohith2883 hardluck but someone already beat you to it

fine :)

**Comment by Ngoakor12** [comment]
@mohith2883 the person working on this is no longer working on it, do you want to have a crack at it?

**Comment by shaheer-2000** [comment]
@Ngoakor12 since this has gone stale (I presume), can I take this up?

**Comment by Ngoakor12** [comment]
@shaheer-2000 sure

**Comment by Ngoakor12** [comment]
@shaheer-2000 sure
