### ISSUE TITLE
Docs: Add a frontend style guide

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#121]
Go over the frontend code checking for patterns in the project or borrow some from other projects' style guides(e.g. airbnb style guide)
- create a `STYLEGUIDE.md` file in the `./frontend` folder
- take the info you've gathered from the research and add it to that file. It doesn't have to be a whole blog post, contribute with whatever you can and we can discuss it

**Comment by trishitchar** [comment]
Hey, I would like to work on this. Thanks!

**Comment by Ngoakor12** [comment]
Sure @trishitchar , I'll assign you now now. Let me know if any questions come up

**Comment by trishitchar** [comment]
@Ngoakor12 
I've done it. Can you please review and merge.

**Comment by Ngoakor12** [comment]
> @Ngoakor12 I've done it. Can you please review and merge.

That was fast, unfortunately I'm not on my machine at the moment so I'll have a look later

**Comment by jahtomini** [comment]
Hey, can I work on this?

**Comment by Ngoakor12** [comment]
Sure @jahtomini , knock yourself out. Take a peek at [this PR](https://github.com/Ngoakor12/coding-resource-finder/pull/122) the previous person was working on and the feedback I left to help your PR go smoother

**Comment by jahtomini** [comment]
You seem to be using Prettier (or ESLint) locally, have you considered adding a config to the project to ensure consistency?

**Comment by Ngoakor12** [comment]
@jahtomini I wouldn't know where to begin at this point to be honest but you're more than welcome to open an issue and hopefully work on the PR. It's fine if can't I will probably learn about it and maybe implement it.

**Comment by jahtomini** [comment]
Alright then will do. It's not much work tbh, there are some pretty good defaults out there. I'll open an issue, and once the PR is merged, I can add the necessary info to the style guide to help contributors.
