### ISSUE TITLE
Docs: Update feature request template

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#127]
The current feature request template has a few sections shown by bolded text and a small description of what that section expects.

**Problem:**
The description of what a section expects stays there and doesn't go away if you choose not to edit or delete it.

**Proposed fix/solution:**
Change the descriptions to be markdown comments instead, that way every section is still explained but disappears after you submit the issue

**Comment by anuragh2002** [comment]
Hey @Ngoakor12 I would like to work on this issue. Can you please assign it to me?

**Comment by Ngoakor12** [comment]
All yours @anuragh2002
