### ISSUE TITLE
Docs: Update bug report template

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#128]
The current bug report template has a few sections shown by bolded text and a small description of what that section expects.

**Problem:**
The description of what a section expects stays there and doesn't go away if you choose not to edit or delete it.

**Proposed fix/solution:**
Change the descriptions to be markdown comments instead, that way every section is still explained but disappears after you submit the issue

**Comment by ShahzaibJutt** [comment]
Assign it to me.

**Comment by Ngoakor12** [comment]
All yours @ShahzaibJutt
