### ISSUE TITLE
Feat: Add storybook for component building

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#130]
**Is your feature request related to a problem? Please describe.**
Yes, I need to have designs ready before I can let people work on features

**Describe the solution you'd like**
Use [Storybook](https://storybook.js.org/) to help with visualizing components without worrying about data and functionality. That way others can sort of work on the designs aswell and implement them as components

**Describe alternatives you've considered**
I keep making designs for things to be implemented and then allow others to work on things when the designs are finalized which is not very sustainable

**Additional context**
At least one component should be added to the storybook to show that everything works as expected. You can ask me if you want  a component to implement.

**Comment by ekiira** [comment]
Hello, 
I would like to work on this, can you please assign it to me.

**Comment by Ngoakor12** [comment]
All yours @ekiira. May I ask what component you plan on adding to storybook to ensure everything is working as expected?

**Comment by ekiira** [comment]
Thanks.
I will be adding the SearchForm Component

**Comment by ekiira** [comment]
Hello @Ngoakor12, upon installing and running the app, It displays errors in the console and a blank page.
Below are screenshots. Please advise on what to do.
<img width="1271" alt="Screenshot 2022-10-11 at 20 20 18" src="https://user-images.githubusercontent.com/57687166/195180560-b4cd909a-2baf-461b-aac7-5065d6751c64.png">
<img width="1265" alt="Screenshot 2022-10-11 at 20 20 41" src="https://user-images.githubusercontent.com/57687166/195180570-0d4d4c5e-3039-4887-b7b9-a8f0c6a0719f.png">

**Comment by Ngoakor12** [comment]
@ekiira I had a look. I believe it's because the backend is not running, the frontend needs it running for it to function as expected.

**Comment by ekiira** [comment]
@Ngoakor12 Yes that was the problem, thank you.

**Comment by Ngoakor12** [comment]
Haha nice, I just added that small bit of error handling. Glad to see it's working great :smile:
