### ISSUE TITLE
Style: Add prettier & eslint configs

### ISSUE THREAD

**Issue by jahtomini** [Ngoakor12/coding-resource-finder#131]
**Is your feature request related to a problem? Please describe.**
Not necessarily, this is aimed at providing consistency and enforcing patterns in the codebase regarding code style.

**Describe the solution you'd like**
Add a .prettierrc file, possibly a .prettierignore file and and an .eslintrc file

**Describe alternatives you've considered**
NIL

**Additional context**
NIL

I'll like to work on this.

**Comment by Ngoakor12** [comment]
Don't know if I should ask, but do you want me to add this as part of hackertoberfest?

**Comment by Ngoakor12** [comment]
Also, I recently merged [a PR](https://github.com/Ngoakor12/coding-resource-finder/pull/132) of some refactoring which may or may not affect this issue if you've already started or the other [styleguide issue](#121 ) you're assigned to

**Comment by jahtomini** [comment]
> Don't know if I should ask, but do you want me to add this as part of hackertoberfest?

Yeah that'll be great 😃 

> Also, I recently merged [a PR](#132) of some refactoring which may or may not affect this issue if you've already started or the other [styleguide issue](#121) you're assigned to

Copy that. I'll take that into consideration
