### ISSUE TITLE
Feat: Add a resources filter 

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#140]
**Is your feature request related to a problem? Please describe.**
Yes, looking for just topics and or just projects can be a pain sometimes.

**Describe the solution you'd like**
Add resources filters chips just below the search form where I can filter by resource type (projects, topics and all)

**Describe alternatives you've considered**
Adding pages for each reasource type but it was too messy

**Additional context**

**Comment by shaheer-2000** [comment]
@Ngoakor12 Sorry for not requesting this issue earlier, but I've submitted a PR #153 that resolves this.

Awaiting your review.

**Comment by Ngoakor12** [comment]
Thanks for taking your time to contribute, it's very appreciated. I'll assign you, but:
- Ideally you should be asking first so that I can assign you so that we don't have more people working on one issue while not aware that someone is working on it.
- The issue was marked not ready because I wanted to figure out how it would look like and where it should live, but it seems you've figured that out
