### ISSUE TITLE
Create a react storybook component for " fetching resources error page" from a design

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#141]
The design can be found on [this figma file](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=249%3A52).

This issue is a subtask of [this bigger parent issue](https://github.com/Ngoakor12/coding-resource-finder/issues/129), you can go there to get a zoomed out/ bigger picture of this task

**Comment by chetanchandel31** [comment]
can i take this up?

**Comment by Ngoakor12** [comment]
@chetanchandel31 sure.
