### ISSUE TITLE
Implement "fetching resources error page" from a react component

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#142]
**Important note**: [This issue](https://github.com/Ngoakor12/coding-resource-finder/issues/141) should be merged before this can be worked on

**Basically how I would solve this**: Conditionally render the error page component when the resources cannot be fetched from the backend server for whatever reason.
<details>
<summary> Detailed suggestion </summary>
In `contextApp.js`:

- create a hasError state defaulted to `false` 
- Replace the alerts with the `setHasError` to `true` setters and conditionally render the specified page if that `hasError` state is true

In `Resources.js` and `Bookmarks.js`:
- conditionally render the `ErrorFetchingResources.js` page component 
</details>

**Another note**: This issue is a subtask of [this bigger parent issue](https://github.com/Ngoakor12/coding-resource-finder/issues/129), you can go there to get a zoomed out/ bigger picture of this task

**Comment by sandilya27** [comment]
I want to work on this

**Comment by Ngoakor12** [comment]
@sandilya27 I'm afraid it's not possible at the moment since the second part of the task(which is the storybook story) is not completed yet. That's why this issue has a "not ready" tag

**Comment by Ngoakor12** [comment]
@sandilya27 It's yours if you're still interested. It's just been unblocked.

**Comment by sandilya27** [comment]
ok I will do it

**Comment by Yash-Yadav-git** [comment]
Hey, @Ngoakor12 I would like this issue to be assigned to me

**Comment by Ngoakor12** [comment]
All yours @Yash-Yadav-git

**Comment by Yash-Yadav-git** [comment]
Can we just error boundary the entire App? So that we have a fallback UI every time we face some kind of network error from server side. If yes, which page should this be? right now I have rendered the ErrorFetchingResources page as the fallback UI.
Is this the expected behavior? or would you want me change it?

**Comment by Ngoakor12** [comment]
Error boundaries... and I'm no expert (I've just read about them😅) seem to encompass different kinds of errors. So I think an error boundary with a generic ui should probably be implemented in the near future.

But for this task I want the error to be specific to the resource fetching part of the app and use the `errorFetchingResources` page component that was created in the previous task.

I might also look into using Suspense in the future but for now, the way I explained everything should be fine. I'll also update the info on my suggested way to fulfill this issue.

**Comment by Ngoakor12** [comment]
@Yash-Yadav-git are you still working on this issue?

**Comment by Yash-Yadav-git** [comment]
@Ngoakor12 Yes, I am.
