### ISSUE TITLE
Create a react storybook component for a "404 not found page" from a design

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#143]
The design can be found on [this figma file](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=251%3A104).

This issue is a subtask of [this bigger parent issue](https://github.com/Ngoakor12/coding-resource-finder/issues/126), you can go there to get a zoomed out/ bigger picture of this task

**Comment by YajanaRao** [comment]
@Ngoakor12 I would like to give this a try today.

**Comment by VSB14** [comment]
Hii @Ngoakor12 , Can you assign this issue to me? Also, do you need this to be implemented using HTML and CSS? please specify.

**Comment by Ngoakor12** [comment]
@YajanaRao sure thing, it's all yours.

@VSB14 React and some CSS but unfortunately @YajanaRao was first so I assigned him instead.

**Comment by YajanaRao** [comment]
@Ngoakor12 Will this be inside pages or component ?

**Comment by Ngoakor12** [comment]
> @Ngoakor12 Will this be inside pages or component ?

pages sounds like the best place

**Comment by VSB14** [comment]
> @YajanaRao sure thing, it's all yours.
> 
> @VSB14 React and some CSS but unfortunately @YajanaRao was first so I assigned him instead.

No problem, ping me if you have any other issue available to work on.

**Comment by YajanaRao** [comment]
@Ngoakor12 As this is a page, I don't think I need to add an event for the click on go to home button right ?

Link to my fork: https://github.com/Ngoakor12/coding-resource-finder/compare/master...YajanaRao:coding-resource-finder:master
![image](https://user-images.githubusercontent.com/38914337/196034916-d4b2ebee-3858-4e74-9fb8-82f940ee76be.png)

**Comment by Ngoakor12** [comment]
> @Ngoakor12 As this is a page, I don't think I need to add an event for the click on go to home button right ? ![image](https://user-images.githubusercontent.com/38914337/196034916-d4b2ebee-3858-4e74-9fb8-82f940ee76be.png)

**You don't need to as this is about more about visually recreating the design as a component**, but it would be nice if the "button"(which should be a React Router link) would do lead to the homepage since it's not a huge thing, implementation wise.

Oh another thing I forgot to mention is that hovering over the button should change the text to the green green colour of the above icon. And of course it needs to be responsive on smaller screens.

**Comment by Ngoakor12** [comment]
> No problem, ping me if you have any other issue available to work on.

@VSB14 there's an identical issue that can be [found here](https://github.com/Ngoakor12/coding-resource-finder/issues/141) if you're farmilliar with using storybook and react

**Comment by YajanaRao** [comment]
@Ngoakor12 I am not able to use <Link> inside the storybook component as the context is not provided.

**Comment by Ngoakor12** [comment]
> @Ngoakor12 I am not able to use <Link> inside the storybook component as the context is not provided. 

It's fine, as long as the main component is done without any errors.

**Comment by YajanaRao** [comment]
Please check this PR: https://github.com/Ngoakor12/coding-resource-finder/pull/147
