### ISSUE TITLE
Implement "404 not found page" from a react component

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#144]
**Important note**: [This issue](https://github.com/Ngoakor12/coding-resource-finder/issues/143) should be merged first before this can be worked on

**Suggestion(How I would solve this)**: Create a catch all react router route and render the above page component for unknown pages instead

**Another note**: This issue is a subtask of [this bigger parent issue](https://github.com/Ngoakor12/coding-resource-finder/issues/129), you can go there to get a zoomed out/ bigger picture of this task

**Comment by harsh0620** [comment]
Hi @Ngoakor12, Can you please assign me this task.

**Comment by Ngoakor12** [comment]
Sure thing @harsh0620, it's all yours
