### ISSUE TITLE
Dockerize (docker-compose) the application

### ISSUE THREAD

**Issue by shaheer-2000** [Ngoakor12/coding-resource-finder#154]
**Is your feature request related to a problem? Please describe.**

- The current deployment process isn't that intuitive, shifting between directories, ensuring both ends are running, issues between different platforms.
- To simplify the deployment process, the application (both frontend and backend) can be `dockerized`.
- [Here's](https://stackoverflow.com/a/62250978) a more detailed list of advantages it'd provide

**Describe the solution you'd like**

- Add `docker` support to this application, so we can just build the `image` and serve it with just a simple `docker-compose up`.

**Describe alternatives you've considered**

- The current deployment process is an alternative, but it's comparatively tedious

**Additional context**

- [`docker-compose docs`](https://docs.docker.com/compose/) for any relevant details regarding `docker-compose`

**Comment by Ngoakor12** [comment]
Ooh I like this. Only dealt with docker a few times but if you can make it happen I'm all for it. It can be used for dev environment until I figure out how to freely host a docker container :sweat_smile: 

JUst make sure to modify the documentation and mention that people with docker installed can you use this method and others can just do it the old way.

**Comment by mohdmulla** [comment]
heya, is this task still available? Can I work on it?

**Comment by Ngoakor12** [comment]
@mohdmulla That is entirely up to @shaheer-2000. I want to give them the chance to work on it first since they opened the issue. If not I'll assign you.

**Comment by shaheer-2000** [comment]
I'll be working on this @Ngoakor12. It's in the queue 😄

**Comment by shaheer-2000** [comment]
@Ngoakor12 I've dockerized the application, do you want me to update the `README.md` in the project root as well? There's a bit of redundancy (cloning the project, running the project) with `CONTRIBUTING.md` there, so I could replace bits of `README.md` with `CONTRIBUTING.md` and add the relevant `docker` information there as well

**Comment by Ngoakor12** [comment]
Makes sense, sure. I've been meaning to get to that but...🙈

**Comment by Ngoakor12** [comment]
I've seen the other PR's you've opened. Will get to them today
