### ISSUE TITLE
Resource type filtering  stuck when both chips are selected and unselected

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#162]
**Describe the bug**

selecting and unselecting resource type chips defaults to all topics

**To Reproduce**

1. select a resource type filter chip
2. unselect it and make sure no resouce type is selected

**Expected behavior**

unselecting a resource chip should result a mix of the resources not only topics

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by MohammadRostami71** [comment]
Hi there. I'm interested in contributing to this repository. I would truly appreciate it if you could assign this to me.

**Comment by Ngoakor12** [comment]
Sure thing, all yours! Let me know if you have any questions.

**Comment by Ngoakor12** [comment]
Everything good @MohammadRostami71?

**Comment by MohammadRostami71** [comment]
Thank you for assing me. i was in travel from university to home. tommorow i will fixing the issue and send pull request.

**Comment by Ngoakor12** [comment]
No pressure, just wanted to confirm if you were still keen to work on it 🤙
