### ISSUE TITLE
Bug: Reload button not reloading the page

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#166]
**Describe the bug**

Reload button not reloading if an error occurs while fetching resources

**To Reproduce**

It should reload the page and try to fetch resources again
**Screenshots**

How the screen looks like when such an error happens
![image](https://user-images.githubusercontent.com/54069197/216130297-9ed27c13-0924-4243-bda0-f7b84df6a100.png)

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by ayobamiseun** [comment]
can i work on this

**Comment by Ngoakor12** [comment]
> can i work on this

Thanks for showing interest but someone already opened [a PR for this issue](https://github.com/Ngoakor12/coding-resource-finder/pull/168)

I'll let you know if the current one falls through

**Comment by Parth1125** [comment]
@Ngoakor12  i have solved the issue please check it and merge the PR
