### ISSUE TITLE
Create storybook for bookmark group icon/buttons

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#169]
This is what it looks like:

![Image](https://user-images.githubusercontent.com/54069197/218315641-cadc8dda-d775-40c9-8cf4-4a0f9d33d7bb.png)

More can be found on [this figma file](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=0%3A1&t=s7ENDfCwolO0xCeZ-0)

**Comment by UzairURK** [comment]
Hi,  Ngoakor12
Can you please assign this issue.
Thanks

**Comment by UzairURK** [comment]
keep updating you.

**Comment by UzairURK** [comment]
@Ngoakor12,
I have run the application using docker but still It displays the page loading or fetching the data. I am unable to upload Screen shot here. Kindly tell me how to fix it.

**Comment by Ngoakor12** [comment]
I had a look. It's working fine on my side. Helping you without screenshots is not ideal

But try running it without docker because that is a complex story on it's own.

1. CD into the backend folder.
2. Make sure that the dependencies are up to date by running: `npm install`
3. Run the server with `npm run dev`
4. Check that you can get the resources from the database by clicking the first link in one of the endpoints that pop up when you run the server, if you're able to see different resources then the frontend should show the resources fine.

**Comment by UzairURK** [comment]
It shows followig.
![Screenshot (28)](https://user-images.githubusercontent.com/82904313/220344483-419b58f6-50b8-40f6-935c-7acced579162.png)
at "http://localhost:2856/". It shows following.
{"resources":"http://localhost:2856/all","topics":"http://localhost:2856/all/topics","projects":"http://localhost:2856/all/projects","resources_page":"http://localhost:2856/all/{page}","topics_page":"http://localhost:2856/all/topics/{page}","projects_page":"http://localhost:2856/all/projects/{page}"}

**Comment by Ngoakor12** [comment]
Select the first link(http://localhost:2856/all)...what does "data" property have?

**Comment by UzairURK** [comment]
It has empty. see following plz.
![Screenshot (31)](https://user-images.githubusercontent.com/82904313/220370349-964bf916-b024-4d33-a948-f4839f0ed971.png)

**Comment by UzairURK** [comment]
I also gets error whenever I run the server in terminal.. see following
![Screenshot (33)](https://user-images.githubusercontent.com/82904313/220374013-7ad3d1a3-db70-488f-8235-70ef0069938e.png)

**Comment by Ngoakor12** [comment]
This last image helps. I know what's wrong.

I just need to think about how to fix it. Please pause a bit, I'll let you know once I've push a fix, thanks for catching it

**Comment by UzairURK** [comment]
@Ngoakor12, Okay

**Comment by Ngoakor12** [comment]
Hey @UzairURK I just pushed a change to add a local database that has a copy of the prod database. You should be good to go now if you're still keen :+1:

**Comment by UzairURK** [comment]
@Ngoakor12,
yes! Sure

**Comment by UzairURK** [comment]
keep updating you...

**Comment by Ngoakor12** [comment]
Hey, any progress on this?

I just noticed that there were some storybook errors. I was able to push a fix just now.

**Comment by UzairURK** [comment]
let me know! when you push a fix

**Comment by Ngoakor12** [comment]
I did on the main branch

**Comment by Ngoakor12** [comment]
Have you made any progress?

**Comment by UzairURK** [comment]
yah! it's about to finish
I will show you the results in a day

**Comment by UzairURK** [comment]
@Ngoakor12 
you have made changes on the main branch? should I clone te whole project newly?

**Comment by Ngoakor12** [comment]
cool thanks :+1:

**Comment by Ngoakor12** [comment]
> @Ngoakor12 you have made changes on the main branch? should I clone te whole project newly?

No you can incorporate new changes by running `git merge master`

**Comment by UzairURK** [comment]
okay

**Comment by UzairURK** [comment]
@Ngoakor12,
can you see that I have added the Story button, So I can push the changes.
![Screenshot (39)](https://user-images.githubusercontent.com/82904313/222904010-9fc70976-629d-4b75-91e3-8985e96fa993.png)

**Comment by Ngoakor12** [comment]
> @Ngoakor12, can you see that I have added the Story button, So I can push the changes. ![Screenshot (39)](https://user-images.githubusercontent.com/82904313/222904010-9fc70976-629d-4b75-91e3-8985e96fa993.png)

I see... here are my initial thoughts looking at the picture above.
- The button doesn't look like the one in the mockup. It's missing some of the outlines/borders
- It **should not** be integrated into the current functionality of the site yet. It should only be a storybook component. Have a look at the files changed tab  on [this PR](#170) I just  made and you'll see what essentially needs to happen

Disclamer I'm only judging by what I see the code could be way better. Open a PR when you're ready and I can give more informed feedback

**Comment by UzairURK** [comment]
let me add borders

**Comment by Ngoakor12** [comment]
Please communicate here, no emails. **Again the two points above still stand**. I think there's a language barrier that's getting the the way of this issue's progress

How much experience do you have with storybook?

**Comment by UzairURK** [comment]
I have a bit of experience but Now I got what exactly you want, let me create BookmarkGroupIcon.stories.js for the group icon. Is it fine?

**Comment by UzairURK** [comment]
see the following images. Is it fine? let me know if changes are required. 
![Screenshot (41)](https://user-images.githubusercontent.com/82904313/222922555-9f9a6bb4-a87b-45c7-9f92-e9bd888704c5.png)
![Screenshot (42)](https://user-images.githubusercontent.com/82904313/222922559-e22603c1-ca36-4afa-92e7-7a78a5c78252.png)

**Comment by Ngoakor12** [comment]
The overall styling looks closer to the mockup...good work 

But this point stil stands...
- It **should not be integrated into the current functionality** of the site yet. It should only be a storybook component. Have a look at the files changed tab on [this PR](https://github.com/Ngoakor12/coding-resource-finder/pull/178) I just made and you'll see what essentially needs to happen

**Comment by UzairURK** [comment]
can you specify which point still stands, kindly mention it. whenever I would have done with CSS and React parts, I will move to the storybook for this component.

**Comment by Ngoakor12** [comment]
> * It **should not be integrated into the current functionality** of the site yet. It should only be a storybook component. Have a look at the files changed tab on [this PR](https://github.com/Ngoakor12/coding-resource-finder/pull/178) I just made and you'll see what essentially needs to happen

.

**Comment by UzairURK** [comment]
but I have integrated it into the site. 

- > would you like to see the whole code? 

- > Should I merge the code into the master branch? 
- > should I create a storybook for Bookmark and then merge it into the master branch?
kindly specify what should I do now, by answering the above questions.

**Comment by Ngoakor12** [comment]
Create a storybook story for it. That's the main task fo the issue you're working on. It **should not be integrated into the actual site** or actual site's components. 

Follow [this PR](#178) I made of a storybook story

**Comment by Ngoakor12** [comment]
- Please read carefully and follow the instructions. I feel I'm always repeating myself when you could just reread what I've written and actually follow the instructions

- You merging the code into master won't affect the main project's code, I would have approve it first and for that you need to open a PR first

**Comment by UzairURK** [comment]
okay! I got...

**Comment by UzairURK** [comment]
created pull request....

**Comment by Ngoakor12** [comment]
Hey thanks, I will have a look at it first thing tomorrow 🤙
