### ISSUE TITLE
Tab navigation order is wrong

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#184]
**Describe the bug**

To top button/icon gets focused on first and then the header get focused on when navigativing with the keyboard

**To Reproduce**

The header items/links should be the first to get focus then the navigation > the  search bar > the resources > load all resources button > to top button/icon. The to top button/icon should be last.

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by Sharmavedant17** [comment]
can i work on this issue?
