### ISSUE TITLE
Feat: Add functional/unit tests

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#27]
Functions to test:

In `./backend/src/format-resources.js`
- [ ] getPages()
- [ ] getPageData()

In `./backend/src/utils.js`
- [ ] getCurrentCollectionName()

In `./backend/src/scrape-resources.js`
- [ ] getHTML()
- [ ] getTopicsFromACN()
- [ ] getProjectsFromACN()
- [ ] getAllResources()

**Comment by Reddomi** [comment]
I'd be interested on working on this! Would be done later than my first contribution, but I am sure to finish this by the end of the month.

**Comment by Ngoakor12** [comment]
No problemo, just a quick question before I assign you... what testing library are you planning on using? I have used [jasmine](https://jasmine.github.io/) before so that's my go to but I would be open to accepting and possibly learning something new(jest, vitest?)

**Comment by Reddomi** [comment]
> No problemo, just a quick question before I assign you... what testing library are you planning on using? I have used [jasmine](https://jasmine.github.io/) before so that's my go to but I would be open to accepting and possibly learning something new(jest, vitest?)

I was intending to use Jest! I don't exactly have much experience testing in JS, so this was the option that seemed the most logical, if you don't mind, that is. (To add, I currently have a university subject that will dig deeper into testing/profiling.)

**Comment by Ngoakor12** [comment]
> I was intending to use Jest! I don't exactly have much experience testing in JS, so this was the option that seemed the most logical, if you don't mind, that is. (To add, I currently have a university subject that will dig deeper into testing/profiling.)

Jest should be fine, noted that some of the files/function names may have changed since the last time I wrote this issue so just know that everything function in the backend folder is fair game. Don't hesitate to shout if need anything :call_me_hand:
