### ISSUE TITLE
Add skeleton resource components on initial load instead of placeholder text("Loading Resources...")

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#29]
Replace text: "Loading Resources..." placeholder when fetching resources with resources skeleton components.

**Design**
Initial colours
![image](https://user-images.githubusercontent.com/54069197/163673581-611296c3-594b-45e4-befa-4098c85e38f4.png)

final colours(as it loads)
![image](https://user-images.githubusercontent.com/54069197/163673661-b64d5bc7-27d5-4c62-8760-1a13505a6b5a.png)

The colour of the cards should change in an infinite smooth-blinker-like animation where one colour fades into the other. Exact styles can be found [here](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=0%3A1)

**Comment by nitin094-hub** [comment]
Can I take up this Issue?

**Comment by Ngoakor12** [comment]
Sure @nitin094-hub, you can. Let me know if you get stuck or have any questions.

**Comment by nitin094-hub** [comment]
Could you plz explain what is this initial color and final color?

**Comment by Ngoakor12** [comment]
The initial and final are just two different grey-ish colours that I want the background colour to fade into each other. Think of an infinite loop from one color to the next but smooth to the point where they blend into each other. Look at [this example](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_animatable)

**Comment by nitin094-hub** [comment]
I have made a pull request. Plz check!

**Comment by Ngoakor12** [comment]
Hey @nitin094-hub are you still working on this?

**Comment by nitin094-hub** [comment]
Ohh srry I forgot.. I am little busy. Can you assign this task to someone?

**Comment by Ngoakor12** [comment]
No problem I'll take it off you. Thanks for trying.
