### ISSUE TITLE
feat: add tabs for all, projects, and topics resources

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#62]
**Is your feature request related to a problem? Please describe.**
When I search for a resource I sometimes just want to browse topics and other times projects.

**Describe the solution you'd like**
Tabs in resource page, above or below the search input and filter shortcuts named: **all**, **topics**,  and **projects**

**Describe alternatives you've considered**
An alternative solution would be to extend the search feature to search by resource type.
Another was to add a shortcut like the topics shortcuts.

**Additional context**
Mockup below. Figma file can be found [here](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=21%3A22)
![image](https://user-images.githubusercontent.com/54069197/167253281-9998cde4-502c-4ea0-8dd8-cfedd08a8cf1.png)

**Comment by matthewbub** [comment]
I could take this :wave:

**Comment by matthewbub** [comment]
whenever you have the opportunity, it might be worth committing a recent version of the `package-lock.json` files in both `/frontend` and the `/backend` directories as I seem to have some unintended modifications in these files 🙂

**Comment by Ngoakor12** [comment]
> whenever you have the opportunity, it might be worth committing a recent version of the `package-lock.json` files in both `/frontend` and the `/backend` directories as I seem to have some unintended modifications in these files slightly_smiling_face

Will do
