### ISSUE TITLE
Refactor: api calls for resources should be fetched when needed

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#64]
**Here's what happens at the moment:**
1. On load/ first render
- first page of visited resources are fetched **and** all resources are fetched concurrently.
2. clicking "Load 20 more resources" button 
- another api call for a page of requested resources is fetched.

**Heres what should happen instead:**
1. On load/ first render for each of  all, topics, and projects:
- first page should be fetched
- all resources matching that page(either all, topics, or projects) should also be fetched concurrently(to make it easier to search all not just first page)
**NOTE:** use promise.all syntax(unless you have a reason not to)

2. clicking the "Load 20 more resources" button should be removed

**Comment by senali-d** [comment]
Can I help to fix the issue?

**Comment by Ngoakor12** [comment]
Yes you can, that would be appreciated. I'll assign it to you now now. Please do let me know if you need me to clarify anything.

**Comment by senali-d** [comment]
Hey [@Ngoakor12](https://github.com/Ngoakor12), I need clarification of this issue.
 1. all data fetch 1st time render
 2. remove "Load 20 more resources" button
 3. What about the "Load all resources button"?
 
 Is this is what you expect. If not provide clear explanation about the issue.

**Comment by Ngoakor12** [comment]
1. Yes, I can explain the flow better if needed.
2. Yes.
3. Leave it. Pressing the "Load all resources" button just replaces the `renderedResources` with all of the resources in a specific page.
