### ISSUE TITLE
Pages; `all`,`topics`, and `projects` are not fully responsive on mobile/smaller screen

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#65]
Here's what it looks like now:
![image](https://user-images.githubusercontent.com/54069197/167876516-f818e811-f0b2-47e9-950e-a9e42517e875.png)

Make sure it's responsive and doesn't spill text.

**NOTE:** keep the pages on one line even on mobile. Don't stack the pages.

**Comment by Ryan-Maddock-96** [comment]
Hi, could I take a look at this please :)
