### ISSUE TITLE
Bug: Direct access via this url `BASE_URL/resources/projects` renders all resources instead of just projects

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#73]
**Describe the bug**
Direct access via this url `BASE_URL/resources/projects` renders all resources instead of just projects
**To Reproduce**
1. Type: `BASE_URL/resources/projects` in the address/search bar
2. Observe the resources rendered, they're are mixed with topics

**Expected behavior**
When you visit the url: `BASE_URL/resources/projects`, the resources rendered should only be projects

**Additional context**
- When accessing the projects via clicking the "projects" tab/nav link, the rendered resources are as expected
- **BASE_URL** is in production https://coding-resource-finder.ngoako.dev/. spinning the backend in localhost will result in the **BASE_URL** being http://localhost:3000

**Comment by dcalhoun286** [comment]
Hi there! I visited your deployed base url, and it looks like you might mean `/all/projects` instead of `/resources/projects`. I tried both; was able to get JSON data to display with the 1st option, but got a `cannot GET` response for the 2nd.

Anywho, when using the url with the 1st option, it appears I am only getting JSON data back for resources that have the "type" property set to "project". When navigating to `/all`, it appears all of the resources are being listed. I used the data generated on the home page as a guide.

**Comment by Ngoakor12** [comment]
> Hi there! I visited your deployed base url, and it looks like you might mean `/all/projects` instead of `/resources/projects`. I tried both; was able to get JSON data to display with the 1st option, but got a `cannot GET` response for the 2nd.
> 
> Anywho, when using the url with the 1st option, it appears I am only getting JSON data back for resources that have the "type" property set to "project". When navigating to `/all`, it appears all of the resources are being listed. I used the data generated on the home page as a guide.

Hey thanks for having a look, it's always great to get new eyes on this project.

I pasted the wrong base_url, that's the backend url, while I meant to post the frontend one instead, I'll change it now now. Good catch.

Both routes you mentioned are all valid and are supposed to both work.
`base_url/resources/projects` is the route set with react router dom for the client. It should fetch it's resources from the backend URL `api_base_url/all/projects`. Maybe I'm fetching from the wrong endpoint, I'll have to double check. But perhaps they should be same to avoid confusion.

**Comment by Ngoakor12** [comment]
no longer needed as I got rid of resource type pages/tabs
