### ISSUE TITLE
Refactor: Replace JSDOM with Cheerio for web scraping

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#78]
[JSDOM](https://github.com/jsdom/jsdom) is a whopping 2.4m (gzipped: 588.6 k) in size. It's only used for web scraping in this project, so it's a bit of an overkill and not worth it imo. [Cheerio](https://github.com/cheeriojs/cheerio) seems like the best lightweight alternative with the only drawback being the syntax from what I've seen so far.

Task:
- [ ] Replace jsdom with cheerio web scraping
- [ ] Uninstall jsdom

**Comment by shaheer-2000** [comment]
@Ngoakor12 I'd also like to take this up as well. Preferably with the appropriate `hacktoberfest` labels, so it can count towards it.

**Comment by Ngoakor12** [comment]
All yours @shaheer-2000
