### ISSUE TITLE
Docs: Add api routes documentation

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#82]
Have a look at the routes in `./backend` folder. Edit the `readme.md` file with some info about the routes exposed by the server.

Add a table with the following column headings; `method`, `endpoint`, `params`, `description`, `return type`. You can play around with the order of the columns, not sure at the moment.

**Comment by ArunimaShukla03** [comment]
hey, I would like to contribute to this.

**Comment by Ngoakor12** [comment]
Sure @ArunimaShukla03 , I'll assign it to you now now. Let me know if you have any questions.

**Comment by ArunimaShukla03** [comment]
what exact information do you want me to add?

**Comment by Ngoakor12** [comment]
Just a small explanation of each endpoint preferably in a table format.

**Comment by abdulahad-07** [comment]
@Ngoakor12 I wish to contribute to this. My suggestion would be to use [swagger](https://swagger.io/) for this.

**Comment by Ngoakor12** [comment]
@abdulahad-07 thanks for showing interest. I'm not too farmiliar with swagger, but I'm not opposed to it as long as:
- [ ] the bundle size is not crazy big
- [ ] it can be intergrated easily and not be a pain to maintain.
- [ ] we can still document the API on GitHub too for people who want to know about the API quick and easy(see first comment)

If so you're more than welcome to open a PR and it will be considered. Let me know if you want to continue so that I can assign you to this issue :)

**Comment by abdulahad-07** [comment]
We can do both. I would like to proceed with the swagger first.

- [ ] The bundle size won't increase much
- [ ] It is easy to integrate and maintain
- [ ] We can do this after swagger

**Comment by Ngoakor12** [comment]
Go ahead :)

**Comment by Ngoakor12** [comment]
Thanks for the contribution @abdulahad-07
