### ISSUE TITLE
Remove resource type pages

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/coding-resource-finder#97]
This specific component is buggy and doesn't fit the site, I'm removing this and opting for a filtering system like the on for topics below the search bar.
Tasks:
- On the UI, remove this part:
![image](https://user-images.githubusercontent.com/54069197/185729998-fd3f34ab-9a64-43ac-bd70-d18556a1b708.png)
- In `App.js`, remove the related routes
- reset  the resources route to just be `/resources` and not `/resources/all`
- update `Context.js` to make sure all types of resources are fetched
- update the `/resources` route page title from `Resources - All | Coding Resource Finder` to just `Resources | Coding Resource Finder`

**Comment by andrewkykoo** [comment]
@Ngoakor12 Hello! Can I work on this issue?

**Comment by Ngoakor12** [comment]
@andrewkykoo sure thanks, let me know if you need me to clarify anything:)
